### PR TITLE
Tkinter implemention

### PR DESCRIPTION
**Pull request by mezgoodle**
image

Everything can change, so write your propositions

### CODE REVIEW

**Comment by VsIG-official** [comment]
Interface is looking good, but need to rework it for Our needs

**Comment by mezgoodle** [comment]
image

I think, we have to connect all our parts quickly and then change the design of the window
I will add:

- inforamtion box
- better names
- etc

It will be better to discuss together: how to improve code and design

**Comment by VsIG-official** [comment]
ok

**Comment by mezgoodle** [comment]
approve?

**Comment by VsIG-official** [comment]
ok

**Review by VsIG-official — APPROVED** [review]

**Pull request merged**
